=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for Quandoo::ReservationSettingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReservationSettingsApi' do
  before do
    # run before each test
    @instance = Quandoo::ReservationSettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReservationSettingsApi' do
    it 'should create an instance of ReservationSettingsApi' do
      expect(@instance).to be_instance_of(Quandoo::ReservationSettingsApi)
    end
  end

  # unit tests for reservation_settings1
  # Get merchant reservation settings
  # This endpoint provides all data that is required to initiate the reservation flow and is not part of the search endpoint.  Example curl: &#x60;&#x60;&#x60; curl https://{host}/v{X}/merchants/15/reservation-settings &#x60;&#x60;&#x60;  Example response:  &#x60;&#x60;&#x60; {   \&quot;areaIds\&quot;: [     {       \&quot;id\&quot;: 2,       \&quot;name\&quot;: \&quot;Garden\&quot;,       \&quot;priority\&quot;: 10     }   ],   \&quot;areaSelectionRequired\&quot;: true,   \&quot;capacities\&quot;: [     1,     2,     3,     4,     5,     6   ],   \&quot;links\&quot;: [     {       \&quot;href\&quot;: \&quot;https://{host}/v{X}/merchants/15\&quot;,       \&quot;method\&quot;: \&quot;GET\&quot;,       \&quot;rel\&quot;: \&quot;parent\&quot;     },     {       \&quot;href\&quot;: \&quot;https://{host}/v{X}/merchants/15/availabilities\&quot;,       \&quot;method\&quot;: \&quot;GET\&quot;,       \&quot;rel\&quot;: \&quot;availability_days\&quot;     },     {       \&quot;href\&quot;: \&quot;https://{host}/v{X}/merchants/15/availabilities/2017-01-01/times\&quot;,       \&quot;method\&quot;: \&quot;GET\&quot;,       \&quot;rel\&quot;: \&quot;availability\&quot;     }   ],   \&quot;merchantNewsletterSelectionRequired\&quot;: true,   \&quot;minimumCapacityForEnquiries\&quot;: 10,   \&quot;onlineReservationInterval\&quot;: 60,   \&quot;reservationEnquiryEnabled\&quot;: true,   \&quot;specialTerms\&quot;: \&quot;This is any custom string for special terms\&quot;,   \&quot;automaticConfirmation\&quot;: true,   \&quot;ccvEnabled\&quot;: true } &#x60;&#x60;&#x60; 
  # @param merchant_id Id of the merchant
  # @param [Hash] opts the optional parameters
  # @return [MerchantReservationSettingsDto]
  describe 'reservation_settings1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
