=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for Quandoo::StatusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @instance = Quandoo::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@instance).to be_instance_of(Quandoo::StatusApi)
    end
  end

  # unit tests for get_status_by_get1
  # Provides information on the status of the service
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_status_by_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_status_by_head1
  # Provides information on the status of the service
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_status_by_head1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
