=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for Quandoo::ValidationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ValidationsApi' do
  before do
    # run before each test
    @instance = Quandoo::ValidationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ValidationsApi' do
    it 'should create an instance of ValidationsApi' do
      expect(@instance).to be_instance_of(Quandoo::ValidationsApi)
    end
  end

  # unit tests for validate_phone_number1
  # Validate phone number
  # This endpoint validates a phone number.  If optional 2-letter country code &#x60;country&#x60; is not specified, the &#x60;phoneNumber&#x60; should be formatted according to E164, which means it is expected to be in the international format with a leading &#x60;\&quot;+\&quot;&#x60; and no spaces or dashes, e.g. &#x60;+4930120765890&#x60;. Otherwise it may have leading zero instead of country code, e.g. &#x60;030120765890&#x60;.  The endpoint will return a status &#x60;HTTP 200&#x60; which means the &#x60;phoneNumber&#x60; is successfully validated. The endpoint will return a status &#x60;HTTP 400&#x60; which means the &#x60;phoneNumber&#x60; is missing or invalid.  Example curl: &#x60;&#x60;&#x60; curl https://{host}/v{X}/validations/phone-numbers?phoneNumber&#x3D;030120765890&amp;country&#x3D;IT &#x60;&#x60;&#x60;  Example response: &#x60;&#x60;&#x60; {   \&quot;errorMessage\&quot;: \&quot;phoneNumber is invalid: 030120765890, country specified is: IT\&quot;,   \&quot;errorType\&quot;: \&quot;PHONE_NUMBER_INVALID\&quot; } &#x60;&#x60;&#x60; 
  # @param phone_number Phone number
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Country code
  # @return [nil]
  describe 'validate_phone_number1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
