=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quandoo::MarketingSettingDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketingSettingDto' do
  before do
    # run before each test
    @instance = Quandoo::MarketingSettingDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketingSettingDto' do
    it 'should create an instance of MarketingSettingDto' do
      expect(@instance).to be_instance_of(Quandoo::MarketingSettingDto)
    end
  end
  describe 'test attribute "marketing_setting_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SMART_OFFERS_AND_DEALS", "PROMO_CODES", "RESTAURANT_RECOMMENDATIONS", "NEWSLETTERS"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.marketing_setting_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "marketing_setting_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ACTIVE", "INACTIVE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.marketing_setting_status = value }.not_to raise_error
      # end
    end
  end

end
