=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quandoo::MerchantReservationEnquiryData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MerchantReservationEnquiryData' do
  before do
    # run before each test
    @instance = Quandoo::MerchantReservationEnquiryData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantReservationEnquiryData' do
    it 'should create an instance of MerchantReservationEnquiryData' do
      expect(@instance).to be_instance_of(Quandoo::MerchantReservationEnquiryData)
    end
  end
  describe 'test attribute "reservation_enquiry"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "customer"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tracking"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
