=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quandoo::StandardOpeningTimesDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StandardOpeningTimesDto' do
  before do
    # run before each test
    @instance = Quandoo::StandardOpeningTimesDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StandardOpeningTimesDto' do
    it 'should create an instance of StandardOpeningTimesDto' do
      expect(@instance).to be_instance_of(Quandoo::StandardOpeningTimesDto)
    end
  end
end
