=begin
#Quandoo API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

# Common files
require 'quandoo/api_client'
require 'quandoo/api_error'
require 'quandoo/version'
require 'quandoo/configuration'

# Models
require 'quandoo/models/agent_tracking'
require 'quandoo/models/area_dto'
require 'quandoo/models/chain_dto'
require 'quandoo/models/changed_review_dto'
require 'quandoo/models/coordinates_dto'
require 'quandoo/models/create_review_dto'
require 'quandoo/models/created_master_customer'
require 'quandoo/models/created_reservation'
require 'quandoo/models/created_reservation_data'
require 'quandoo/models/created_reservation_enquiry'
require 'quandoo/models/created_reservation_enquiry_data'
require 'quandoo/models/customer_data_list'
require 'quandoo/models/customer_dto'
require 'quandoo/models/customer_response'
require 'quandoo/models/customer_review_data'
require 'quandoo/models/customer_statistics_data'
require 'quandoo/models/deal_data'
require 'quandoo/models/document_dto'
require 'quandoo/models/error_response'
require 'quandoo/models/get_reservation_enquiry_data'
require 'quandoo/models/get_review_dto'
require 'quandoo/models/get_reviews_dto'
require 'quandoo/models/image_dto'
require 'quandoo/models/link_relation_dto'
require 'quandoo/models/location_dto'
require 'quandoo/models/marketing_setting_dto'
require 'quandoo/models/merchant_address_dto'
require 'quandoo/models/merchant_availability_days_dto'
require 'quandoo/models/merchant_availability_dto'
require 'quandoo/models/merchant_availability_dto_list'
require 'quandoo/models/merchant_customer'
require 'quandoo/models/merchant_customer_data'
require 'quandoo/models/merchant_details_dto'
require 'quandoo/models/merchant_details_dto_list'
require 'quandoo/models/merchant_menu_category_dto'
require 'quandoo/models/merchant_menu_dto'
require 'quandoo/models/merchant_menu_item_dto'
require 'quandoo/models/merchant_menus_dto'
require 'quandoo/models/merchant_reservation'
require 'quandoo/models/merchant_reservation_data'
require 'quandoo/models/merchant_reservation_enquiry'
require 'quandoo/models/merchant_reservation_enquiry_data'
require 'quandoo/models/merchant_reservation_settings_dto'
require 'quandoo/models/merchant_subscription'
require 'quandoo/models/merchant_vault_settings_dto'
require 'quandoo/models/merchant_with_recommendations_dto'
require 'quandoo/models/opening_times_dto'
require 'quandoo/models/reservation_data'
require 'quandoo/models/reservation_data_list'
require 'quandoo/models/reservation_details'
require 'quandoo/models/reservation_enquiry_message_data'
require 'quandoo/models/reservation_enquiry_message_list'
require 'quandoo/models/reservation_menu_data'
require 'quandoo/models/reservation_menu_item_data'
require 'quandoo/models/rest_cookie'
require 'quandoo/models/review_dto'
require 'quandoo/models/review_dto_list'
require 'quandoo/models/standard_opening_times_dto'
require 'quandoo/models/tag_group_dto'
require 'quandoo/models/tracking'
require 'quandoo/models/translated_tag_dto'
require 'quandoo/models/update_reservation_data'
require 'quandoo/models/update_reservation_enquiry_data'
require 'quandoo/models/update_review_dto'

# APIs
require 'quandoo/api/availabilities_api'
require 'quandoo/api/customers_api'
require 'quandoo/api/menus_api'
require 'quandoo/api/merchants_api'
require 'quandoo/api/reservation_enquiries_api'
require 'quandoo/api/reservation_settings_api'
require 'quandoo/api/reservations_api'
require 'quandoo/api/reviews_api'
require 'quandoo/api/status_api'
require 'quandoo/api/validations_api'

module Quandoo
  class << self
    # Customize default settings for the SDK using block.
    #   Quandoo.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
